/**
 * TTS Queue — Stream Koko
 * All audio is generated by the Kokoro service in the main process.
 * The renderer requests synthesis via IPC, receives base64 WAV audio, and
 * plays it with an HTML5 <audio> element.  The same audio data is forwarded
 * to the OBS overlay via WebSocket.
 */

export interface TTSRequest {
  id: string;
  text: string;
  voiceId: string;
  speed: number;
  viewerId?: string;
  username?: string;
}

export interface TTSQueueItem extends TTSRequest {
  status: 'pending' | 'playing' | 'completed' | 'error';
  error?: string;
  audioData?: string;   // base64 WAV (cached after first synthesis)
}

export class TTSQueue {
  private queue: TTSQueueItem[] = [];
  private playing = false;
  private currentItem: TTSQueueItem | null = null;
  private onQueueUpdateCb?: (q: TTSQueueItem[]) => void;
  private onItemStartCb?: (item: TTSQueueItem) => void;
  private onItemCompleteCb?: (item: TTSQueueItem) => void;

  add(req: TTSRequest): void {
    this.queue.push({ ...req, status: 'pending' });
    this.notifyUpdate();
    if (!this.playing) this.processNext();
  }

  clear(): void {
    this.queue = this.queue.filter(i => i.status === 'playing');
    this.notifyUpdate();
  }

  onQueueUpdate(cb: (q: TTSQueueItem[]) => void): void   { this.onQueueUpdateCb = cb; }
  onItemStart(cb: (item: TTSQueueItem) => void): void    { this.onItemStartCb  = cb; }
  onItemComplete(cb: (item: TTSQueueItem) => void): void { this.onItemCompleteCb = cb; }

  getQueue(): TTSQueueItem[] { return [...this.queue]; }
  getCurrentItem(): TTSQueueItem | null { return this.currentItem; }

  private notifyUpdate(): void {
    this.onQueueUpdateCb?.([...this.queue]);
  }

  private async processNext(): Promise<void> {
    if (this.queue.length === 0) {
      this.playing = false;
      this.currentItem = null;
      return;
    }

    this.playing = true;
    const item = this.queue[0];
    this.currentItem = item;
    item.status = 'playing';
    this.notifyUpdate();
    this.onItemStartCb?.(item);

    try {
      // Synthesise via Kokoro (main process)
      if (!item.audioData) {
        const result = await window.api.invoke('tts:synthesize', {
          text: item.text,
          voiceId: item.voiceId,
          speed: item.speed
        });

        if (result.success && result.audioData) {
          item.audioData = result.audioData;
        } else {
          throw new Error(result.error ?? 'Kokoro synthesis failed');
        }
      }

      // Forward to OBS overlay
      await window.api.invoke('obs:broadcastEvent', {
        type: 'start',
        item: {
          id: item.id,
          text: item.text,
          username: item.username,
          viewerId: item.viewerId,
          voiceId: item.voiceId,
          speed: item.speed,
          audioData: item.audioData
        }
      }).catch(() => {});   // OBS might not be running — ignore

      // Play audio in-app (unless muted for OBS)
      await this.playAudio(item);

      // Signal OBS that playback is complete
      await window.api.invoke('obs:broadcastEvent', {
        type: 'complete',
        item: { id: item.id }
      }).catch(() => {});

      item.status = 'completed';
      this.onItemCompleteCb?.(item);
    } catch (err) {
      item.status = 'error';
      item.error  = String(err);
      console.error('[TTS Queue] Error:', err);
    }

    this.queue.shift();
    this.notifyUpdate();
    setTimeout(() => this.processNext(), 100);
  }

  private async playAudio(item: TTSQueueItem): Promise<void> {
    // Respect "mute in-app when OBS is running"
    try {
      const obsStatus = await window.api.invoke('obs:getStatus');
      const muteInApp = await window.api.invoke('db:getSetting', 'tts_mute_in_app');

      if (obsStatus.running && muteInApp === 'true') {
        // OBS handles playback — wait for it to finish
        const r = await window.api.invoke('obs:waitForAudioComplete');
        if (!r.success) console.warn('[TTS Queue] OBS playback timeout');
        return;
      }
    } catch {
      // OBS status check failed — continue with in-app playback
    }

    if (!item.audioData) return;

    return new Promise<void>((resolve, reject) => {
      const audio = new Audio(`data:audio/wav;base64,${item.audioData}`);
      audio.onended  = () => resolve();
      audio.onerror  = (e) => reject(new Error(`Audio playback error: ${e}`));
      audio.play().catch(reject);
    });
  }
}

let instance: TTSQueue | null = null;
export function getTTSQueue(): TTSQueue {
  if (!instance) instance = new TTSQueue();
  return instance;
}
